// ─── Action Plan Builder ─────────────────────────────────────────────────────
// Generates a phased execution roadmap with checkable tasks and agent prompts.

import type { Briefing } from "../schema";
import { getDependencyChain, getCapabilities } from "../capabilities";
import { recommendVibeTools, recommendDatabases, recommendDeployPlatform } from "../stackRules";

interface ActionPlanOptions {
  lang: "es" | "en";
}

const l = {
  es: {
    title: "Plan de Acción",
    phase: "Fase",
    task: "Tarea",
    deliverable: "Entregable",
    doneWhen: "Hecho cuando",
    estTime: "Tiempo estimado",
    prompt: "Prompt para tu agente",
    generatedBy: "Generado por Vibe Coding Hub",
  },
  en: {
    title: "Action Plan",
    phase: "Phase",
    task: "Task",
    deliverable: "Deliverable",
    doneWhen: "Done when",
    estTime: "Estimated time",
    prompt: "Prompt for your agent",
    generatedBy: "Generated by Vibe Coding Hub",
  },
};

export function buildActionPlan(briefing: Briefing, options: ActionPlanOptions): string {
  const t = l[options.lang];
  const capIds = getDependencyChain(briefing.capabilities.selected);
  const caps = getCapabilities(capIds);
  const toolRec = recommendVibeTools(briefing);
  const dbRec = recommendDatabases(briefing);
  const deployRec = recommendDeployPlatform(briefing);
  const topTool = toolRec.top3[0]?.name || "your vibe coding tool";
  const topDb = dbRec.top3[0]?.name || "your database";

  const isEs = options.lang === "es";
  const lines: string[] = [];
  const add = (s: string) => lines.push(s);
  const blank = () => lines.push("");

  add(`# ${t.title}`);
  add(`**${briefing.identity.name || "—"}**`);
  blank();

  // ── Phase 1: Research & Design ──
  add(`## ${t.phase} 1: ${isEs ? "Investigación y Diseño" : "Research & Design"}`);
  add(`**${t.estTime}:** ${isEs ? "2-4 horas" : "2-4 hours"}`);
  blank();
  add(`- [ ] ${isEs ? "Recopilar 5-10 referencias visuales de Godly.website, Dribbble o Refero" : "Collect 5-10 visual references from Godly.website, Dribbble, or Refero"}`);
  add(`- [ ] ${isEs ? "Definir paleta de colores y tipografía" : "Define color palette and typography"}`);
  add(`- [ ] ${isEs ? "Subir documentación del stack elegido a NotebookLM" : "Upload chosen stack documentation to NotebookLM"}`);
  add(`- [ ] ${isEs ? "Generar preguntas fundamentadas en NotebookLM para el agente" : "Generate source-grounded questions in NotebookLM for the agent"}`);
  blank();
  add(`> **${t.prompt}:**`);
  add(`> "${isEs
    ? `Sube la documentación oficial de ${topDb} a NotebookLM. Pregunta: "¿Cuáles son las mejores prácticas para configurar ${topDb} para un proyecto de tipo ${briefing.identity.projectType}?" Extrae la respuesta textual para usarla como contexto del agente.`
    : `Upload the official ${topDb} documentation to NotebookLM. Ask: "What are the best practices for configuring ${topDb} for a ${briefing.identity.projectType} project?" Extract the verbatim answer to use as agent context.`
  }"`);
  blank();

  add(`**${t.deliverable}:** ${isEs ? "Mood board + prompts contextualizados de NotebookLM" : "Mood board + contextualized NotebookLM prompts"}`);
  add(`**${t.doneWhen}:** ${isEs ? "Tienes al menos 3 prompts listos para pegar en tu agente" : "You have at least 3 prompts ready to paste into your agent"}`);
  blank();

  // ── Phase 2: Database & Architecture ──
  if (topDb !== "No database needed") {
    add(`## ${t.phase} 2: ${isEs ? "Base de Datos y Arquitectura" : "Database & Architecture"}`);
    add(`**${t.estTime}:** ${isEs ? "1-2 horas" : "1-2 hours"}`);
    blank();
    add(`- [ ] ${isEs ? `Crear proyecto en ${topDb}` : `Create project in ${topDb}`}`);
    add(`- [ ] ${isEs ? "Ejecutar el DDL generado en el TRD" : "Execute the DDL generated in the TRD"}`);
    if (capIds.includes("auth")) {
      add(`- [ ] ${isEs ? "Configurar autenticación (email + contraseña)" : "Set up authentication (email + password)"}`);
      add(`- [ ] ${isEs ? "Activar Row Level Security (RLS)" : "Enable Row Level Security (RLS)"}`);
    }
    if (capIds.includes("payments")) {
      add(`- [ ] ${isEs ? "Crear cuenta de Stripe y obtener claves API" : "Create Stripe account and get API keys"}`);
    }
    blank();
    add(`> **${t.prompt}:**`);
    add(`> "${isEs
      ? `Configura ${topDb} para mi proyecto. Ejecuta este DDL: [pegar DDL del TRD]. Configura RLS para que cada usuario solo vea sus propios datos.`
      : `Set up ${topDb} for my project. Execute this DDL: [paste DDL from TRD]. Configure RLS so each user can only see their own data.`
    }"`);
    blank();
    add(`**${t.deliverable}:** ${isEs ? `${topDb} configurado con esquema y políticas de seguridad` : `${topDb} configured with schema and security policies`}`);
    add(`**${t.doneWhen}:** ${isEs ? "Puedes insertar y consultar datos desde la consola" : "You can insert and query data from the console"}`);
    blank();
  }

  // ── Phase 3: Build with Vibe Tool ──
  const phaseNum = topDb !== "No database needed" ? 3 : 2;
  add(`## ${t.phase} ${phaseNum}: ${isEs ? `Construcción con ${topTool}` : `Build with ${topTool}`}`);
  add(`**${t.estTime}:** ${isEs ? "4-8 horas" : "4-8 hours"}`);
  blank();
  add(`- [ ] ${isEs ? `Abrir ${topTool} y pegar el prompt maestro (contexto de NotebookLM + PRD resumido)` : `Open ${topTool} and paste the master prompt (NotebookLM context + summarized PRD)`}`);
  caps.forEach((cap) => {
    const label = isEs ? cap.labelEs : cap.labelEn;
    add(`- [ ] ${isEs ? `Implementar: ${label}` : `Implement: ${label}`}`);
  });
  add(`- [ ] ${isEs ? "Verificar en el preview que la UI coincide con las referencias visuales" : "Verify in preview that the UI matches visual references"}`);
  blank();
  add(`> **${t.prompt}:**`);
  add(`> "${isEs
    ? `Crea un ${briefing.identity.projectType} llamado "${briefing.identity.name}". Incluye las siguientes capacidades: ${caps.map(c => c.labelEs).join(", ")}. Usa ${topDb} como base de datos. Sigue estas referencias visuales: [pegar referencias]. El tono debe ser: ${briefing.branding.toneAdjectives.join(", ") || "profesional y moderno"}.`
    : `Create a ${briefing.identity.projectType} called "${briefing.identity.name}". Include these capabilities: ${caps.map(c => c.labelEn).join(", ")}. Use ${topDb} as the database. Follow these visual references: [paste references]. The tone should be: ${briefing.branding.toneAdjectives.join(", ") || "professional and modern"}.`
  }"`);
  blank();
  add(`**${t.deliverable}:** ${isEs ? "Codebase funcional con preview en vivo" : "Working codebase with live preview"}`);
  add(`**${t.doneWhen}:** ${isEs ? "Todas las capacidades seleccionadas están funcionando en el preview" : "All selected capabilities are working in preview"}`);
  blank();

  // ── Phase 4: GitHub ──
  add(`## ${t.phase} ${phaseNum + 1}: ${isEs ? "Subir a GitHub" : "Push to GitHub"}`);
  add(`**${t.estTime}:** ${isEs ? "15 minutos" : "15 minutes"}`);
  blank();
  add(`- [ ] ${isEs ? `Exportar código desde ${topTool} a GitHub` : `Export code from ${topTool} to GitHub`}`);
  add(`- [ ] ${isEs ? "Verificar que el repositorio contiene todos los archivos" : "Verify the repository contains all files"}`);
  add(`- [ ] ${isEs ? "Añadir CLAUDE.md, AGENTS.md y .cursorrules al repo" : "Add CLAUDE.md, AGENTS.md, and .cursorrules to the repo"}`);
  blank();
  add(`**${t.deliverable}:** ${isEs ? "Repositorio GitHub con historial de versiones" : "GitHub repository with version history"}`);
  add(`**${t.doneWhen}:** ${isEs ? "El código está en GitHub y es cloneable" : "Code is on GitHub and cloneable"}`);
  blank();

  // ── Phase 5: Deploy ──
  add(`## ${t.phase} ${phaseNum + 2}: ${isEs ? "Despliegue" : "Deploy"}`);
  add(`**${t.estTime}:** ${isEs ? "15 minutos" : "15 minutes"}`);
  blank();
  add(`- [ ] ${isEs ? `Conectar repositorio GitHub a ${deployRec.platform}` : `Connect GitHub repository to ${deployRec.platform}`}`);
  add(`- [ ] ${isEs ? "Configurar variables de entorno" : "Configure environment variables"}`);
  add(`- [ ] ${isEs ? "Verificar que el build de producción pasa" : "Verify production build passes"}`);
  add(`- [ ] ${isEs ? "Verificar URL pública en vivo" : "Verify live public URL"}`);
  if (briefing.identity.projectType === "pwa") {
    add(`- [ ] ${isEs ? "Verificar instalabilidad PWA y funcionamiento offline" : "Verify PWA installability and offline functionality"}`);
  }
  blank();
  add(`**${t.deliverable}:** ${isEs ? "URL pública en vivo con auto-deploy" : "Live public URL with auto-deploy"}`);
  add(`**${t.doneWhen}:** ${isEs ? "La app es accesible desde cualquier navegador" : "The app is accessible from any browser"}`);
  blank();

  // ── Phase 6: Iteration ──
  add(`## ${t.phase} ${phaseNum + 3}: ${isEs ? "Iteración y Refinamiento" : "Iteration & Refinement"}`);
  add(`**${t.estTime}:** ${isEs ? "Continuo" : "Ongoing"}`);
  blank();
  add(`- [ ] ${isEs ? "Revisar Lighthouse y corregir < 90" : "Review Lighthouse and fix scores < 90"}`);
  add(`- [ ] ${isEs ? "Probar en móvil y tablet" : "Test on mobile and tablet"}`);
  add(`- [ ] ${isEs ? "Revisar accesibilidad con Axe DevTools" : "Review accessibility with Axe DevTools"}`);
  add(`- [ ] ${isEs ? "Añadir datos reales y probar flujos completos" : "Add real data and test complete flows"}`);
  blank();
  add(`> **${t.prompt} (${isEs ? "diagnóstico de errores" : "error diagnosis"}):**`);
  add(`> "${isEs
    ? `Estoy viendo este error en mi app: [pegar error]. Mi stack es: ${topTool} + ${topDb} + ${deployRec.platform}. ¿Cuál es la causa más probable y cómo lo arreglo?`
    : `I'm seeing this error in my app: [paste error]. My stack is: ${topTool} + ${topDb} + ${deployRec.platform}. What's the most likely cause and how do I fix it?`
  }"`);
  blank();

  add("---");
  add(`*${t.generatedBy} · ${new Date().toISOString().split("T")[0]}*`);

  return lines.join("\n");
}
