// ─── PRD Builder ─────────────────────────────────────────────────────────────
// Generates a Product Requirements Document in Markdown from a Briefing.
// Pure TypeScript, deterministic, zero dependencies beyond the engine.

import type { Briefing } from "../schema";
import {
  getCapabilities, getAllRequirements, getAllUserStories,
  getAllRisks, getAllNfrs, getAllUxScreens, getDependencyChain,
} from "../capabilities";

interface PrdOptions {
  lang: "es" | "en";
}

const labels = {
  es: {
    title: "Documento de Requisitos de Producto (PRD)",
    vision: "Visión y Problema",
    objectives: "Objetivos",
    nonObjectives: "No-Objetivos",
    personas: "Personas",
    userStories: "Historias de Usuario",
    scope: "Alcance por Fases",
    mvp: "MVP (Versión Mínima Viable)",
    v1: "v1.0",
    future: "Futuro",
    funcRequirements: "Requisitos Funcionales",
    nfRequirements: "Requisitos No Funcionales",
    screens: "Inventario de Pantallas",
    risks: "Riesgos y Supuestos",
    metrics: "Métricas de Éxito",
    glossary: "Glosario",
    priority: "Prioridad",
    must: "Obligatorio",
    should: "Recomendado",
    could: "Opcional",
    given: "Dado",
    when: "Cuando",
    then: "Entonces",
    persona: "Persona",
    pain: "Dolor principal",
    context: "Contexto de uso",
    techLevel: "Nivel técnico",
    device: "Dispositivo primario",
    asA: "Como",
    iWantTo: "quiero",
    soThat: "para",
    acceptanceCriteria: "Criterios de Aceptación",
    generatedBy: "Generado por Vibe Coding Hub",
    projectName: "Proyecto",
    projectType: "Tipo de proyecto",
    objective: "Objetivo",
  },
  en: {
    title: "Product Requirements Document (PRD)",
    vision: "Vision & Problem Statement",
    objectives: "Objectives",
    nonObjectives: "Non-Objectives",
    personas: "Personas",
    userStories: "User Stories",
    scope: "Scope by Phase",
    mvp: "MVP (Minimum Viable Product)",
    v1: "v1.0",
    future: "Future",
    funcRequirements: "Functional Requirements",
    nfRequirements: "Non-Functional Requirements",
    screens: "Screen Inventory",
    risks: "Risks & Assumptions",
    metrics: "Success Metrics",
    glossary: "Glossary",
    priority: "Priority",
    must: "Must Have",
    should: "Should Have",
    could: "Nice to Have",
    given: "Given",
    when: "When",
    then: "Then",
    persona: "Persona",
    pain: "Main pain",
    context: "Usage context",
    techLevel: "Tech level",
    device: "Primary device",
    asA: "As a",
    iWantTo: "I want to",
    soThat: "so that",
    acceptanceCriteria: "Acceptance Criteria",
    generatedBy: "Generated by Vibe Coding Hub",
    projectName: "Project",
    projectType: "Project type",
    objective: "Objective",
  },
};

const projectTypeLabels: Record<string, { es: string; en: string }> = {
  landing: { es: "Landing Page", en: "Landing Page" },
  portfolio: { es: "Portfolio / Marca Personal", en: "Portfolio / Personal Brand" },
  store: { es: "Tienda Online / E-Commerce", en: "Online Store / E-Commerce" },
  saas: { es: "SaaS / Web App", en: "SaaS / Web App" },
  dashboard: { es: "Dashboard / Panel de Admin", en: "Dashboard / Admin Panel" },
  crm: { es: "CRM / Gestor de Clientes", en: "CRM / Client Manager" },
  funnel: { es: "Embudo de Ventas", en: "Sales Funnel" },
  blog: { es: "Blog / Plataforma de Contenido", en: "Blog / Content Platform" },
  slides: { es: "Presentación HTML", en: "HTML Slide Deck" },
  mobile: { es: "App Móvil Nativa", en: "Native Mobile App" },
  pwa: { es: "Progressive Web App (PWA)", en: "Progressive Web App (PWA)" },
  booking: { es: "Sistema de Reservas", en: "Booking / Scheduling System" },
  marketplace: { es: "Marketplace", en: "Marketplace" },
  internal: { es: "Herramienta Interna", en: "Internal Tool" },
};

const objectiveLabels: Record<string, { es: string; en: string }> = {
  personal: { es: "Proyecto personal", en: "Personal project" },
  directSale: { es: "Venta directa", en: "Direct sale" },
  subscription: { es: "Suscripción", en: "Subscription" },
  clientProject: { es: "Proyecto para cliente", en: "Client project" },
};

export function buildPrd(briefing: Briefing, options: PrdOptions): string {
  const l = labels[options.lang];
  const capIds = getDependencyChain(briefing.capabilities.selected);
  const caps = getCapabilities(capIds);
  const reqs = getAllRequirements(capIds);
  const stories = getAllUserStories(capIds);
  const risks = getAllRisks(capIds);
  const nfrs = getAllNfrs(capIds);
  const screens = getAllUxScreens(capIds);

  const ptLabel = projectTypeLabels[briefing.identity.projectType]?.[options.lang] || briefing.identity.projectType;
  const objLabel = objectiveLabels[briefing.identity.objective]?.[options.lang] || briefing.identity.objective;

  const lines: string[] = [];
  const add = (s: string) => lines.push(s);
  const blank = () => lines.push("");

  // ── Header ──
  add(`# ${l.title}`);
  add(`**${l.projectName}:** ${briefing.identity.name || "—"}`);
  add(`**${l.projectType}:** ${ptLabel}`);
  add(`**${l.objective}:** ${objLabel}`);
  if (briefing.identity.tagline) add(`> ${briefing.identity.tagline}`);
  blank();

  // ── Vision ──
  add(`## 1. ${l.vision}`);
  blank();
  if (options.lang === "es") {
    add(`**${briefing.identity.name}** es un proyecto de tipo **${ptLabel}** con el objetivo de **${objLabel.toLowerCase()}**.`);
    if (briefing.users.personas[0]?.mainPain) {
      add(`El problema principal que resuelve: *${briefing.users.personas[0].mainPain}*.`);
    }
  } else {
    add(`**${briefing.identity.name}** is a **${ptLabel}** project with the objective of **${objLabel.toLowerCase()}**.`);
    if (briefing.users.personas[0]?.mainPain) {
      add(`The main problem it solves: *${briefing.users.personas[0].mainPain}*.`);
    }
  }
  blank();

  // ── Objectives ──
  add(`## 2. ${l.objectives}`);
  blank();
  if (options.lang === "es") {
    add(`- Entregar un ${ptLabel} funcional con las capacidades seleccionadas`);
    add(`- Servir a ${briefing.users.personas.map(p => p.role).join(", ")} de manera efectiva`);
    if (briefing.identity.projectType === "pwa") add("- Funcionar offline e instalarse como aplicación nativa");
    if (caps.find(c => c.id === "payments")) add("- Procesar pagos de forma segura");
    if (caps.find(c => c.id === "auth")) add("- Gestionar autenticación y sesiones de usuario");
  } else {
    add(`- Deliver a functional ${ptLabel} with the selected capabilities`);
    add(`- Serve ${briefing.users.personas.map(p => p.role).join(", ")} effectively`);
    if (briefing.identity.projectType === "pwa") add("- Work offline and install as a native-like application");
    if (caps.find(c => c.id === "payments")) add("- Process payments securely");
    if (caps.find(c => c.id === "auth")) add("- Manage user authentication and sessions");
  }
  blank();

  // ── Non-Objectives ──
  add(`## 3. ${l.nonObjectives}`);
  blank();
  if (options.lang === "es") {
    add("- No se incluye aplicación móvil nativa (salvo que el tipo de proyecto lo indique)");
    add("- No se incluyen integraciones no seleccionadas en el briefing");
    add("- No se garantiza escalabilidad empresarial sin validación de arquitectura");
  } else {
    add("- Native mobile app is not included (unless the project type requires it)");
    add("- Integrations not selected in the briefing are excluded");
    add("- Enterprise scalability is not guaranteed without architecture review");
  }
  blank();

  // ── Personas ──
  add(`## 4. ${l.personas}`);
  blank();
  briefing.users.personas.forEach((p, i) => {
    add(`### ${l.persona} ${i + 1}: ${p.role || `User ${i + 1}`}`);
    if (p.mainPain) add(`- **${l.pain}:** ${p.mainPain}`);
    if (p.context) add(`- **${l.context}:** ${p.context}`);
    add(`- **${l.techLevel}:** ${p.techLevel}`);
    add(`- **${l.device}:** ${briefing.users.primaryDevice}`);
    blank();
  });

  // ── User Stories ──
  if (stories.length > 0) {
    add(`## 5. ${l.userStories}`);
    blank();
    stories.forEach((s, i) => {
      add(`### US-${String(i + 1).padStart(2, "0")}`);
      add(`**${l.asA}** ${s.persona}, **${l.iWantTo}** ${s.action}, **${l.soThat}** ${s.benefit}.`);
      blank();
      add(`**${l.acceptanceCriteria}:**`);
      s.acceptance.forEach((a) => {
        add(`- ${a}`);
      });
      blank();
    });
  }

  // ── Scope by Phase ──
  add(`## 6. ${l.scope}`);
  blank();
  const mustReqs = reqs.filter(r => r.priority === "must");
  const shouldReqs = reqs.filter(r => r.priority === "should");
  const couldReqs = reqs.filter(r => r.priority === "could");

  add(`### ${l.mvp}`);
  mustReqs.forEach(r => add(`- [${r.id}] ${r.text}`));
  blank();

  add(`### ${l.v1}`);
  shouldReqs.forEach(r => add(`- [${r.id}] ${r.text}`));
  blank();

  if (couldReqs.length > 0) {
    add(`### ${l.future}`);
    couldReqs.forEach(r => add(`- [${r.id}] ${r.text}`));
    blank();
  }

  // ── Functional Requirements ──
  add(`## 7. ${l.funcRequirements}`);
  blank();
  add(`| ID | ${options.lang === "es" ? "Requisito" : "Requirement"} | ${l.priority} |`);
  add("|---|---|---|");
  reqs.forEach(r => {
    const pLabel = r.priority === "must" ? l.must : r.priority === "should" ? l.should : l.could;
    add(`| ${r.id} | ${r.text} | ${pLabel} |`);
  });
  blank();

  // ── Non-Functional Requirements ──
  if (nfrs.length > 0) {
    add(`## 8. ${l.nfRequirements}`);
    blank();
    nfrs.forEach(n => add(`- ${n}`));
    blank();
  }

  // ── Screen Inventory ──
  if (screens.length > 0) {
    add(`## 9. ${l.screens}`);
    blank();
    screens.forEach(s => add(`- \`${s}\``));
    blank();
  }

  // ── Risks ──
  if (risks.length > 0) {
    add(`## 10. ${l.risks}`);
    blank();
    risks.forEach(r => add(`- ⚠️ ${r}`));
    blank();
  }

  // ── Success Metrics ──
  add(`## 11. ${l.metrics}`);
  blank();
  if (options.lang === "es") {
    add("- Tiempo de carga inicial < 3 segundos (LCP)");
    add("- Tasa de error < 1% en flujos críticos");
    if (caps.find(c => c.id === "auth")) add("- Tasa de registro completado > 70%");
    if (caps.find(c => c.id === "payments")) add("- Tasa de conversión de checkout > 3%");
    add("- Puntuación Lighthouse ≥ 90 en todas las categorías");
  } else {
    add("- Initial load time < 3 seconds (LCP)");
    add("- Error rate < 1% on critical flows");
    if (caps.find(c => c.id === "auth")) add("- Registration completion rate > 70%");
    if (caps.find(c => c.id === "payments")) add("- Checkout conversion rate > 3%");
    add("- Lighthouse score ≥ 90 across all categories");
  }
  blank();

  // ── Footer ──
  add("---");
  add(`*${l.generatedBy} · ${new Date().toISOString().split("T")[0]}*`);

  return lines.join("\n");
}
