// ─── Prompt Pack Builder ─────────────────────────────────────────────────────
// Generates AI agent prompts + starter repository files:
// CLAUDE.md, AGENTS.md, .cursorrules

import type { Briefing } from "../schema";
import { getDependencyChain, getCapabilities } from "../capabilities";
import { recommendVibeTools, recommendDatabases, recommendDeployPlatform } from "../stackRules";

interface PromptPackOptions {
  lang: "es" | "en";
}

const l = {
  es: {
    title: "Paquete de Prompts",
    masterPrompt: "Prompt Maestro de Arranque",
    phasePrompts: "Prompts por Fase",
    diagnosticPrompt: "Prompt de Diagnóstico de Errores",
    a11yReviewPrompt: "Prompt de Revisión de Accesibilidad",
    visualReviewPrompt: "Prompt de Revisión Visual",
    starterFiles: "Archivos de Arranque para el Repositorio",
    copyInstruction: "Copia este archivo en la raíz de tu repositorio",
    generatedBy: "Generado por Vibe Coding Hub",
  },
  en: {
    title: "Prompt Pack",
    masterPrompt: "Master Startup Prompt",
    phasePrompts: "Phase Prompts",
    diagnosticPrompt: "Error Diagnostic Prompt",
    a11yReviewPrompt: "Accessibility Review Prompt",
    visualReviewPrompt: "Visual Review Prompt",
    starterFiles: "Starter Repository Files",
    copyInstruction: "Copy this file to the root of your repository",
    generatedBy: "Generated by Vibe Coding Hub",
  },
};

export function buildPromptPack(briefing: Briefing, options: PromptPackOptions): string {
  const t = l[options.lang];
  const isEs = options.lang === "es";
  const capIds = getDependencyChain(briefing.capabilities.selected);
  const caps = getCapabilities(capIds);
  const toolRec = recommendVibeTools(briefing);
  const dbRec = recommendDatabases(briefing);
  const deployRec = recommendDeployPlatform(briefing);
  const topTool = toolRec.top3[0]?.name || "your vibe coding tool";
  const topDb = dbRec.top3[0]?.name || "your database";
  const capList = caps.map(c => isEs ? c.labelEs : c.labelEn).join(", ");

  const lines: string[] = [];
  const add = (s: string) => lines.push(s);
  const blank = () => lines.push("");

  add(`# ${t.title}`);
  add(`**${briefing.identity.name || "—"}**`);
  blank();

  // ── Master Prompt ──
  add(`## 1. ${t.masterPrompt}`);
  blank();
  add(isEs ? "> Copia y pega este prompt como primera instrucción en tu agente de vibe coding." : "> Copy and paste this prompt as the first instruction to your vibe coding agent.");
  blank();
  add("```");
  add(`You are an expert full-stack engineer. I'm building "${briefing.identity.name || "App"}", a ${briefing.identity.projectType} with these characteristics:`);
  add("");
  add(`OBJECTIVE: ${briefing.identity.tagline || briefing.identity.objective}`);
  add(`TYPE: ${briefing.identity.projectType}`);
  add(`AUDIENCE: ${briefing.users.personas.map(p => p.role).join(", ") || "General users"}`);
  add(`PRIMARY DEVICE: ${briefing.users.primaryDevice}`);
  add(`CAPABILITIES: ${caps.map(c => c.labelEn).join(", ") || "None specified"}`);
  add(`DATABASE: ${topDb}`);
  add(`DEPLOY: ${deployRec.platform}`);
  add(`VISUAL TONE: ${briefing.branding.toneAdjectives.join(", ") || "professional and modern"}`);
  add(`BASE COLOR: ${briefing.branding.baseColor}`);
  add(`DENSITY: ${briefing.branding.density}`);
  add("");
  add("TECHNICAL CONSTRAINTS:");
  add("- Use React + Vite + TypeScript");
  add("- CSS with OKLCH variables (see attached design tokens)");
  add("- Validation with Zod on client and server");
  add("- Accessible components (WCAG 2.1 AA)");
  add("- Every interactive component must have: empty, loading, error, success, and disabled states");
  add(`- Fonts: Space Grotesk (display), Inter (body), JetBrains Mono (code)`);
  if (briefing.identity.projectType === "pwa") {
    add("- PWA: complete manifest, service worker with Workbox, cache strategy by resource type");
  }
  add("");
  add("Start by building the project structure and main navigation.");
  add("```");
  blank();

  // ── Diagnostic Prompt ──
  add(`## 2. ${t.diagnosticPrompt}`);
  blank();
  add(isEs ? "> Úsalo cuando encuentres un error." : "> Use when you encounter an error.");
  blank();
  add("```");
  add("I'm seeing this error in my application:");
  add("[PASTE ERROR HERE]");
  add("");
  add(`My stack: React + Vite + TypeScript + ${topDb} + ${deployRec.platform}`);
  add(`Implemented capabilities: ${caps.map(c => c.labelEn).join(", ") || "None"}`);
  add("");
  add("1. What is the most likely root cause?");
  add("2. What is the most direct fix?");
  add("3. Could this error affect other components?");
  add("```");
  blank();

  // ── A11y Review Prompt ──
  add(`## 3. ${t.a11yReviewPrompt}`);
  blank();
  add("```");
  add("Review this component for WCAG 2.1 AA accessibility compliance:");
  add("[PASTE COMPONENT CODE]");
  add("");
  add("Check:");
  add("- Color contrast ≥ 4.5:1");
  add("- Keyboard navigation (Tab, Enter, Escape)");
  add("- Correct ARIA attributes");
  add("- Image alt text");
  add("- Form labels");
  add("- Touch targets ≥ 44×44px");
  add("- `prefers-reduced-motion` support");
  add("```");
  blank();

  // ── Visual Review Prompt ──
  add(`## 4. ${t.visualReviewPrompt}`);
  blank();
  add("```");
  add(`Review my ${briefing.identity.projectType} UI against these visual references:`);
  add("[PASTE SCREENSHOT OR LINK]");
  add("");
  add(`Desired tone: ${briefing.branding.toneAdjectives.join(", ") || "professional and modern"}`);
  add(`Density: ${briefing.branding.density}`);
  add("");
  add("What spacing, typography, color, or animation adjustments would improve consistency with the references?");
  add("```");
  blank();

  // ── Security Audit Prompt (Cyber Neo-inspired) ──
  const secLabel = isEs ? "Prompt de Auditoría de Seguridad" : "Security Audit Prompt";
  add(`## 5. ${secLabel}`);
  blank();
  add(isEs
    ? "> Pégalo en Claude Code antes de publicar tu app. Cubre los 11 dominios que revisa Cyber Neo."
    : "> Paste in Claude Code before publishing your app. Covers the 11 security domains Cyber Neo audits.");
  blank();
  add("```");
  add(isEs
    ? `Haz una revisión de seguridad completa de este proyecto (${briefing.identity.name || "App"}). Revisa cada uno de los siguientes dominios y reporta hallazgos clasificados por gravedad: Critical, High, Medium, Low.`
    : `Do a complete security review of this project (${briefing.identity.name || "App"}). Review each of the following domains and report findings classified by severity: Critical, High, Medium, Low.`);
  add("");
  add(isEs ? "Dominios a revisar:" : "Domains to review:");
  add(isEs ? "1. Código (SAST): variables hardcodeadas, eval(), innerHTML con datos de usuario, concatenación de SQL" : "1. Code (SAST): hardcoded secrets, eval(), innerHTML with user data, SQL concatenation");
  add(isEs ? "2. Autenticación: expiración de tokens, logout, bloqueo por intentos fallidos" : "2. Authentication: token expiry, logout, lockout on failed attempts");
  add(isEs ? "3. Criptografía: algoritmos obsoletos, secretos débiles, hashing de contraseñas" : "3. Cryptography: weak algorithms, weak secrets, password hashing");
  add(isEs ? "4. Secretos filtrados: tokens, API keys o credenciales en el código o en el bundle" : "4. Leaked secrets: tokens, API keys, or credentials in code or bundle");
  add(isEs ? "5. Dependencias: paquetes con CVEs conocidos en package.json / pnpm-lock.yaml" : "5. Dependencies: packages with known CVEs in package.json / pnpm-lock.yaml");
  add(isEs ? "6. Seguridad Web: ausencia de CSP, X-Frame-Options, X-Content-Type-Options, CORS mal configurado" : "6. Web Security: missing CSP, X-Frame-Options, X-Content-Type-Options, misconfigured CORS");
  add(isEs ? "7. Supply Chain: lockfile ausente o bypasseable, dependencias sin fijar" : "7. Supply Chain: missing or bypassable lockfile, unpinned dependencies");
  add(isEs ? "8. CI/CD: secretos expuestos en logs, actions sin pinning de versión" : "8. CI/CD: secrets exposed in logs, actions without version pinning");
  add(isEs ? "9. Manejo de Errores: stack traces expuestos al usuario, errores sin capturar" : "9. Error Handling: stack traces exposed to user, uncaught errors");
  add(isEs ? "10. Logging: datos sensibles (contraseñas, tokens, PII) en logs" : "10. Logging: sensitive data (passwords, tokens, PII) in logs");
  if (capIds.includes("auth")) {
    add(isEs ? "11. Control de Acceso: rutas o endpoints accesibles sin autenticación" : "11. Access Control: routes or endpoints accessible without authentication");
  }
  add("");
  add(isEs
    ? "Para cada hallazgo indica: archivo exacto + línea, descripción del riesgo, y la corrección recomendada. Empieza por Critical y High. No modifiques ningún archivo hasta que yo lo confirme."
    : "For each finding indicate: exact file + line, risk description, and recommended fix. Start with Critical and High. Do not modify any file until I confirm.");
  add("```");
  // ── Starter Files ──
  add(`## 6. ${t.starterFiles}`);

  add(`### \`CLAUDE.md\``);
  add(`> ${t.copyInstruction}`);
  blank();
  add("```markdown");
  add(`# ${briefing.identity.name}`);
  add("");
  add(`## Project Overview`);
  add(`${briefing.identity.tagline || briefing.identity.name} — a ${briefing.identity.projectType} project.`);
  add("");
  add("## Tech Stack");
  add("- **Frontend:** React + Vite + TypeScript");
  add(`- **Database:** ${topDb}`);
  add(`- **Deploy:** ${deployRec.platform}`);
  add(`- **Styling:** Tailwind CSS v4 with OKLCH tokens`);
  add(`- **Fonts:** Space Grotesk (display), Inter (body), JetBrains Mono (mono)`);
  add("");
  add("## Key Capabilities");
  caps.forEach((cap) => {
    add(`- ${cap.labelEn}`);
  });
  add("");
  add("## Development Commands");
  add("```bash");
  add("pnpm install      # Install dependencies");
  add("pnpm dev           # Start dev server");
  add("pnpm check         # TypeScript type check");
  add("pnpm build:static  # Production build");
  add("```");
  add("");
  add("## Code Conventions");
  add("- Validate all inputs with Zod");
  add("- Use semantic HTML and ARIA attributes");
  add("- Every interactive component needs 5 states: empty, loading, error, success, disabled");
  add("- Use CSS custom properties for design tokens (see index.css)");
  add("- Prefer named exports over default exports for components");
  add("");
  add("## Security Rules");
  add("- Never hardcode secrets, API keys or tokens — use environment variables");
  add("- Validate all user inputs with Zod on both client and server");
  add("- Set CSP, X-Frame-Options and X-Content-Type-Options headers in deploy config");
  add("- Never log sensitive data (passwords, tokens, PII)");
  add("- Audit dependencies for CVEs before shipping");
  add("```");
  blank();

  // AGENTS.md
  add(`### \`AGENTS.md\``);
  add(`> ${t.copyInstruction}`);
  blank();
  add("```markdown");
  add(`# Agent Instructions for ${briefing.identity.name}`);
  add("");
  add("## Rules");
  add("- Always use TypeScript strict mode");
  add("- Validate all user inputs with Zod schemas");
  add("- Use OKLCH color values — never hex in component styles");
  add("- Components must handle all 5 states (empty, loading, error, success, disabled)");
  add("- Follow mobile-first responsive design");
  add("- Preserve existing comments and documentation");
  add("- Run `pnpm check` before committing");
  add("");
  add("## Security Rules");
  add("- Never hardcode secrets or API keys — use environment variables");
  add("- Validate all inputs with Zod on client AND server");
  add("- Set security headers (CSP, X-Frame-Options) in netlify.toml / vercel.json");
  add("- Never expose stack traces or internal errors to end users");
  add("- Never log passwords, tokens, or PII");
  add("```");
  blank();

  // .cursorrules
  add(`### \`.cursorrules\``);
  add(`> ${t.copyInstruction}`);
  blank();
  add("```");
  add(`Project: ${briefing.identity.name}`);
  add(`Type: ${briefing.identity.projectType}`);
  add(`Stack: React + Vite + TypeScript + ${topDb} + ${deployRec.platform}`);
  add("");
  add("Rules:");
  add("- Use TypeScript strict mode");
  add("- Validate inputs with Zod");
  add("- Use OKLCH for all colors");
  add("- Components need 5 states: empty, loading, error, success, disabled");
  add("- Mobile-first responsive design");
  add("- WCAG 2.1 AA accessibility");
  add("- Run pnpm check before committing");
  add("```");
  blank();

  add("---");
  add(`*${t.generatedBy} · ${new Date().toISOString().split("T")[0]}*`);

  return lines.join("\n");
}
