// ─── Prompt Pack Builder ─────────────────────────────────────────────────────
// Generates AI agent prompts + starter repository files:
// CLAUDE.md, AGENTS.md, .cursorrules

import type { Briefing } from "../schema";
import { getDependencyChain, getCapabilities } from "../capabilities";
import { recommendVibeTools, recommendDatabases, recommendDeployPlatform } from "../stackRules";

interface PromptPackOptions {
  lang: "es" | "en";
}

const l = {
  es: {
    title: "Paquete de Prompts",
    masterPrompt: "Prompt Maestro de Arranque",
    phasePrompts: "Prompts por Fase",
    diagnosticPrompt: "Prompt de Diagnóstico de Errores",
    a11yReviewPrompt: "Prompt de Revisión de Accesibilidad",
    visualReviewPrompt: "Prompt de Revisión Visual",
    starterFiles: "Archivos de Arranque para el Repositorio",
    copyInstruction: "Copia este archivo en la raíz de tu repositorio",
    generatedBy: "Generado por Vibe Coding Hub",
  },
  en: {
    title: "Prompt Pack",
    masterPrompt: "Master Startup Prompt",
    phasePrompts: "Phase Prompts",
    diagnosticPrompt: "Error Diagnostic Prompt",
    a11yReviewPrompt: "Accessibility Review Prompt",
    visualReviewPrompt: "Visual Review Prompt",
    starterFiles: "Starter Repository Files",
    copyInstruction: "Copy this file to the root of your repository",
    generatedBy: "Generated by Vibe Coding Hub",
  },
};

export function buildPromptPack(briefing: Briefing, options: PromptPackOptions): string {
  const t = l[options.lang];
  const isEs = options.lang === "es";
  const capIds = getDependencyChain(briefing.capabilities.selected);
  const caps = getCapabilities(capIds);
  const toolRec = recommendVibeTools(briefing);
  const dbRec = recommendDatabases(briefing);
  const deployRec = recommendDeployPlatform(briefing);
  const topTool = toolRec.top3[0]?.name || "your vibe coding tool";
  const topDb = dbRec.top3[0]?.name || "your database";
  const capList = caps.map(c => isEs ? c.labelEs : c.labelEn).join(", ");

  const lines: string[] = [];
  const add = (s: string) => lines.push(s);
  const blank = () => lines.push("");

  add(`# ${t.title}`);
  add(`**${briefing.identity.name || "—"}**`);
  blank();

  // ── Master Prompt ──
  add(`## 1. ${t.masterPrompt}`);
  blank();
  add(isEs ? "> Copia y pega este prompt como primera instrucción en tu agente de vibe coding." : "> Copy and paste this prompt as the first instruction to your vibe coding agent.");
  blank();
  add("```");
  if (isEs) {
    add(`Eres un ingeniero full-stack experto. Estoy construyendo "${briefing.identity.name}", un ${briefing.identity.projectType} con estas características:`);
    add("");
    add(`OBJETIVO: ${briefing.identity.tagline || briefing.identity.objective}`);
    add(`TIPO: ${briefing.identity.projectType}`);
    add(`AUDIENCIA: ${briefing.users.personas.map(p => p.role).join(", ")}`);
    add(`DISPOSITIVO PRIMARIO: ${briefing.users.primaryDevice}`);
    add(`CAPACIDADES: ${capList}`);
    add(`BASE DE DATOS: ${topDb}`);
    add(`DESPLIEGUE: ${deployRec.platform}`);
    add(`TONO VISUAL: ${briefing.branding.toneAdjectives.join(", ") || "profesional y moderno"}`);
    add(`COLOR BASE: ${briefing.branding.baseColor}`);
    add(`DENSIDAD: ${briefing.branding.density}`);
    add("");
    add("RESTRICCIONES TÉCNICAS:");
    add("- Usa React + Vite + TypeScript");
    add("- CSS con variables OKLCH (ver tokens adjuntos)");
    add("- Validación con Zod en cliente y servidor");
    add("- Componentes accesibles (WCAG 2.1 AA)");
    add("- Cada componente interactivo debe tener: estado vacío, cargando, error, éxito y deshabilitado");
    add(`- Fuentes: Space Grotesk (display), Inter (body), JetBrains Mono (code)`);
    if (briefing.identity.projectType === "pwa") {
      add("- PWA: manifest completo, service worker con Workbox, estrategia de caché por tipo de recurso");
    }
    add("");
    add("Empieza construyendo la estructura del proyecto y la navegación principal.");
  } else {
    add(`You are an expert full-stack engineer. I'm building "${briefing.identity.name}", a ${briefing.identity.projectType} with these characteristics:`);
    add("");
    add(`OBJECTIVE: ${briefing.identity.tagline || briefing.identity.objective}`);
    add(`TYPE: ${briefing.identity.projectType}`);
    add(`AUDIENCE: ${briefing.users.personas.map(p => p.role).join(", ")}`);
    add(`PRIMARY DEVICE: ${briefing.users.primaryDevice}`);
    add(`CAPABILITIES: ${capList}`);
    add(`DATABASE: ${topDb}`);
    add(`DEPLOY: ${deployRec.platform}`);
    add(`VISUAL TONE: ${briefing.branding.toneAdjectives.join(", ") || "professional and modern"}`);
    add(`BASE COLOR: ${briefing.branding.baseColor}`);
    add(`DENSITY: ${briefing.branding.density}`);
    add("");
    add("TECHNICAL CONSTRAINTS:");
    add("- Use React + Vite + TypeScript");
    add("- CSS with OKLCH variables (see attached tokens)");
    add("- Validation with Zod on client and server");
    add("- Accessible components (WCAG 2.1 AA)");
    add("- Every interactive component must have: empty, loading, error, success, and disabled states");
    add(`- Fonts: Space Grotesk (display), Inter (body), JetBrains Mono (code)`);
    if (briefing.identity.projectType === "pwa") {
      add("- PWA: complete manifest, service worker with Workbox, cache strategy by resource type");
    }
    add("");
    add("Start by building the project structure and main navigation.");
  }
  add("```");
  blank();

  // ── Diagnostic Prompt ──
  add(`## 2. ${t.diagnosticPrompt}`);
  blank();
  add(isEs ? "> Úsalo cuando encuentres un error." : "> Use when you encounter an error.");
  blank();
  add("```");
  if (isEs) {
    add("Estoy viendo este error en mi aplicación:");
    add("[PEGAR ERROR AQUÍ]");
    add("");
    add(`Mi stack: React + Vite + TypeScript + ${topDb} + ${deployRec.platform}`);
    add(`Capacidades implementadas: ${capList}`);
    add("");
    add("1. ¿Cuál es la causa raíz más probable?");
    add("2. ¿Cuál es el fix más directo?");
    add("3. ¿Podría este error afectar a otros componentes?");
  } else {
    add("I'm seeing this error in my application:");
    add("[PASTE ERROR HERE]");
    add("");
    add(`My stack: React + Vite + TypeScript + ${topDb} + ${deployRec.platform}`);
    add(`Implemented capabilities: ${capList}`);
    add("");
    add("1. What is the most likely root cause?");
    add("2. What is the most direct fix?");
    add("3. Could this error affect other components?");
  }
  add("```");
  blank();

  // ── A11y Review Prompt ──
  add(`## 3. ${t.a11yReviewPrompt}`);
  blank();
  add("```");
  if (isEs) {
    add("Revisa este componente para cumplimiento de accesibilidad WCAG 2.1 AA:");
    add("[PEGAR CÓDIGO DEL COMPONENTE]");
    add("");
    add("Verifica:");
    add("- Contraste de color ≥ 4.5:1");
    add("- Navegación por teclado (Tab, Enter, Escape)");
    add("- Atributos ARIA correctos");
    add("- Alt text en imágenes");
    add("- Labels en formularios");
    add("- Touch targets ≥ 44×44px");
    add("- Soporte para `prefers-reduced-motion`");
  } else {
    add("Review this component for WCAG 2.1 AA accessibility compliance:");
    add("[PASTE COMPONENT CODE]");
    add("");
    add("Check:");
    add("- Color contrast ≥ 4.5:1");
    add("- Keyboard navigation (Tab, Enter, Escape)");
    add("- Correct ARIA attributes");
    add("- Image alt text");
    add("- Form labels");
    add("- Touch targets ≥ 44×44px");
    add("- `prefers-reduced-motion` support");
  }
  add("```");
  blank();

  // ── Visual Review Prompt ──
  add(`## 4. ${t.visualReviewPrompt}`);
  blank();
  add("```");
  if (isEs) {
    add(`Revisa la UI de mi ${briefing.identity.projectType} contra estas referencias visuales:`);
    add("[PEGAR CAPTURA O ENLACE]");
    add("");
    add(`Tono deseado: ${briefing.branding.toneAdjectives.join(", ") || "profesional y moderno"}`);
    add(`Densidad: ${briefing.branding.density}`);
    add("");
    add("¿Qué ajustes de espaciado, tipografía, color o animación mejorarían la coherencia con las referencias?");
  } else {
    add(`Review my ${briefing.identity.projectType} UI against these visual references:`);
    add("[PASTE SCREENSHOT OR LINK]");
    add("");
    add(`Desired tone: ${briefing.branding.toneAdjectives.join(", ") || "professional and modern"}`);
    add(`Density: ${briefing.branding.density}`);
    add("");
    add("What spacing, typography, color, or animation adjustments would improve consistency with the references?");
  }
  add("```");
  blank();

  // ── Starter Files ──
  add(`## 5. ${t.starterFiles}`);
  blank();

  // CLAUDE.md
  add(`### \`CLAUDE.md\``);
  add(`> ${t.copyInstruction}`);
  blank();
  add("```markdown");
  add(`# ${briefing.identity.name}`);
  add("");
  add(`## Project Overview`);
  add(`${briefing.identity.tagline || briefing.identity.name} — a ${briefing.identity.projectType} project.`);
  add("");
  add("## Tech Stack");
  add("- **Frontend:** React + Vite + TypeScript");
  add(`- **Database:** ${topDb}`);
  add(`- **Deploy:** ${deployRec.platform}`);
  add(`- **Styling:** Tailwind CSS v4 with OKLCH tokens`);
  add(`- **Fonts:** Space Grotesk (display), Inter (body), JetBrains Mono (mono)`);
  add("");
  add("## Key Capabilities");
  caps.forEach((cap) => {
    add(`- ${cap.labelEn}`);
  });
  add("");
  add("## Development Commands");
  add("```bash");
  add("pnpm install      # Install dependencies");
  add("pnpm dev           # Start dev server");
  add("pnpm check         # TypeScript type check");
  add("pnpm build:static  # Production build");
  add("```");
  add("");
  add("## Code Conventions");
  add("- Validate all inputs with Zod");
  add("- Use semantic HTML and ARIA attributes");
  add("- Every interactive component needs 5 states: empty, loading, error, success, disabled");
  add("- Use CSS custom properties for design tokens (see index.css)");
  add("- Prefer named exports over default exports for components");
  add("```");
  blank();

  // AGENTS.md
  add(`### \`AGENTS.md\``);
  add(`> ${t.copyInstruction}`);
  blank();
  add("```markdown");
  add(`# Agent Instructions for ${briefing.identity.name}`);
  add("");
  add("## Rules");
  add("- Always use TypeScript strict mode");
  add("- Validate all user inputs with Zod schemas");
  add("- Use OKLCH color values — never hex in component styles");
  add("- Components must handle all 5 states (empty, loading, error, success, disabled)");
  add("- Follow mobile-first responsive design");
  add("- Preserve existing comments and documentation");
  add("- Run `pnpm check` before committing");
  add("```");
  blank();

  // .cursorrules
  add(`### \`.cursorrules\``);
  add(`> ${t.copyInstruction}`);
  blank();
  add("```");
  add(`Project: ${briefing.identity.name}`);
  add(`Type: ${briefing.identity.projectType}`);
  add(`Stack: React + Vite + TypeScript + ${topDb} + ${deployRec.platform}`);
  add("");
  add("Rules:");
  add("- Use TypeScript strict mode");
  add("- Validate inputs with Zod");
  add("- Use OKLCH for all colors");
  add("- Components need 5 states: empty, loading, error, success, disabled");
  add("- Mobile-first responsive design");
  add("- WCAG 2.1 AA accessibility");
  add("- Run pnpm check before committing");
  add("```");
  blank();

  add("---");
  add(`*${t.generatedBy} · ${new Date().toISOString().split("T")[0]}*`);

  return lines.join("\n");
}
