// ─── TRD Builder ─────────────────────────────────────────────────────────────
// Generates a Technical Requirements Document in Markdown from a Briefing.
// Includes Mermaid diagrams and executable DDL (SQL for Postgres/Supabase).

import type { Briefing } from "../schema";
import {
  getCapabilities, getAllDataModel, getAllNfrs, getAllRequirements,
  getDependencyChain, type DataModelEntry,
} from "../capabilities";
import { recommendVibeTools, recommendDatabases, recommendDeployPlatform } from "../stackRules";

interface TrdOptions {
  lang: "es" | "en";
}

const l = {
  es: {
    title: "Documento de Requisitos Técnicos (TRD)",
    archSection: "Arquitectura Propuesta",
    archRationale: "Justificación",
    diagram: "Diagrama de Componentes",
    dataFlowDiagram: "Diagrama de Flujo de Datos",
    dataModel: "Modelo de Datos",
    ddl: "DDL — SQL Listo para Ejecutar",
    apiContracts: "Contratos de API",
    authSection: "Autenticación y Autorización",
    pwaSection: "Estrategia PWA",
    perfSection: "Presupuestos de Rendimiento",
    securitySection: "Seguridad",
    nfrSection: "Requisitos No Funcionales",
    testSection: "Plan de Pruebas",
    cicdSection: "CI/CD y Entornos",
    traceMatrix: "Matriz de Trazabilidad",
    toolRec: "Herramienta Recomendada",
    dbRec: "Base de Datos Recomendada",
    deployRec: "Plataforma de Despliegue",
    score: "Puntuación",
    reasons: "Razones",
    tradeoffs: "Contrapartidas",
    whyNotOthers: "¿Por qué no las otras?",
    generatedBy: "Generado por Vibe Coding Hub",
  },
  en: {
    title: "Technical Requirements Document (TRD)",
    archSection: "Proposed Architecture",
    archRationale: "Rationale",
    diagram: "Component Diagram",
    dataFlowDiagram: "Data Flow Diagram",
    dataModel: "Data Model",
    ddl: "DDL — Ready-to-Execute SQL",
    apiContracts: "API Contracts",
    authSection: "Authentication & Authorization",
    pwaSection: "PWA Strategy",
    perfSection: "Performance Budgets",
    securitySection: "Security",
    nfrSection: "Non-Functional Requirements",
    testSection: "Test Plan",
    cicdSection: "CI/CD & Environments",
    traceMatrix: "Traceability Matrix",
    toolRec: "Recommended Tool",
    dbRec: "Recommended Database",
    deployRec: "Deploy Platform",
    score: "Score",
    reasons: "Reasons",
    tradeoffs: "Trade-offs",
    whyNotOthers: "Why not the others?",
    generatedBy: "Generated by Vibe Coding Hub",
  },
};

function generateMermaidArchitecture(briefing: Briefing, capIds: string[]): string {
  const lines: string[] = ["```mermaid", "graph TD"];
  lines.push('  Client["🖥️ Client (React + Vite)"]');

  const hasAuth = capIds.includes("auth");
  const hasPayments = capIds.includes("payments");
  const hasRealtime = capIds.includes("realtime");
  const hasFileUpload = capIds.includes("fileUpload");
  const hasLlm = capIds.includes("llm");
  const hasEmail = capIds.includes("email");
  const hasSearch = capIds.includes("search");

  if (hasAuth) lines.push('  Auth["🔐 Auth Service"]');
  lines.push('  API["⚙️ API Layer"]');
  lines.push('  DB["🗄️ Database"]');
  if (hasPayments) lines.push('  Stripe["💳 Stripe"]');
  if (hasRealtime) lines.push('  WS["⚡ WebSocket / Realtime"]');
  if (hasFileUpload) lines.push('  Storage["📁 Object Storage"]');
  if (hasLlm) lines.push('  LLM["🤖 LLM API"]');
  if (hasEmail) lines.push('  Email["📧 Email Service"]');
  if (hasSearch) lines.push('  Search["🔍 Search Engine"]');
  lines.push('  CDN["🌐 CDN / Deploy"]');

  // Connections
  lines.push("  Client --> API");
  if (hasAuth) {
    lines.push("  Client --> Auth");
    lines.push("  Auth --> DB");
  }
  lines.push("  API --> DB");
  if (hasPayments) lines.push("  API --> Stripe");
  if (hasRealtime) {
    lines.push("  Client --> WS");
    lines.push("  WS --> DB");
  }
  if (hasFileUpload) lines.push("  API --> Storage");
  if (hasLlm) lines.push("  API --> LLM");
  if (hasEmail) lines.push("  API --> Email");
  if (hasSearch) {
    lines.push("  API --> Search");
    lines.push("  Search --> DB");
  }
  lines.push("  Client --> CDN");

  lines.push("```");
  return lines.join("\n");
}

function generateMermaidDataFlow(briefing: Briefing, capIds: string[]): string {
  const lines: string[] = ["```mermaid", "sequenceDiagram"];
  lines.push("  actor User");
  lines.push("  participant App as React App");
  lines.push("  participant API as API Layer");
  lines.push("  participant DB as Database");

  if (capIds.includes("auth")) {
    lines.push("  User->>App: Open app");
    lines.push("  App->>API: Check session");
    lines.push("  API->>DB: Validate token");
    lines.push("  DB-->>API: Session valid");
    lines.push("  API-->>App: Authenticated");
  }

  lines.push("  User->>App: Perform action");
  lines.push("  App->>API: API request");
  lines.push("  API->>DB: Query/Mutate");
  lines.push("  DB-->>API: Result");
  lines.push("  API-->>App: Response");
  lines.push("  App-->>User: Updated UI");

  if (capIds.includes("realtime")) {
    lines.push("  Note over App,DB: Real-time subscription active");
    lines.push("  DB-->>App: Live update");
    lines.push("  App-->>User: Instant UI refresh");
  }

  lines.push("```");
  return lines.join("\n");
}

function generateDdl(dataModel: DataModelEntry[]): string {
  if (dataModel.length === 0) return "";

  const lines: string[] = ["```sql", "-- DDL generated by Vibe Coding Hub", "-- Target: PostgreSQL / Supabase", ""];

  dataModel.forEach((table) => {
    lines.push(`CREATE TABLE IF NOT EXISTS ${table.table} (`);
    table.fields.forEach((f, i) => {
      const suffix = f.note ? ` ${f.note}` : "";
      const comma = i < table.fields.length - 1 ? "," : "";
      lines.push(`  ${f.name} ${f.type.toUpperCase()}${suffix}${comma}`);
    });
    lines.push(");");
    lines.push("");
  });

  // Add RLS policies if auth is involved
  const hasUserCol = dataModel.some((t) => t.fields.some((f) => f.name === "user_id"));
  if (hasUserCol) {
    lines.push("-- Row Level Security (RLS) policies");
    dataModel.forEach((table) => {
      if (table.fields.some((f) => f.name === "user_id")) {
        lines.push(`ALTER TABLE ${table.table} ENABLE ROW LEVEL SECURITY;`);
        lines.push(`CREATE POLICY "Users can access own ${table.table}" ON ${table.table}`);
        lines.push(`  FOR ALL USING (auth.uid() = user_id);`);
        lines.push("");
      }
    });
  }

  lines.push("```");
  return lines.join("\n");
}

export function buildTrd(briefing: Briefing, options: TrdOptions): string {
  const t = l[options.lang];
  const capIds = getDependencyChain(briefing.capabilities.selected);
  const caps = getCapabilities(capIds);
  const dataModel = getAllDataModel(capIds);
  const nfrs = getAllNfrs(capIds);
  const reqs = getAllRequirements(capIds);

  const toolRec = recommendVibeTools(briefing);
  const dbRec = recommendDatabases(briefing);
  const deployRec = recommendDeployPlatform(briefing);

  const lines: string[] = [];
  const add = (s: string) => lines.push(s);
  const blank = () => lines.push("");

  // ── Header ──
  add(`# ${t.title}`);
  add(`**${briefing.identity.name || "—"}**`);
  blank();

  // ── Architecture ──
  add(`## 1. ${t.archSection}`);
  blank();

  // Tool recommendation
  add(`### ${t.toolRec}`);
  blank();
  toolRec.top3.forEach((opt, i) => {
    const pct = Math.round((opt.score / opt.maxScore) * 100);
    add(`**${i + 1}. ${opt.name}** — ${t.score}: ${pct}%`);
    if (opt.reasons.length > 0) {
      add(`- ${t.reasons}: ${opt.reasons.join("; ")}`);
    }
    if (opt.tradeoffs.length > 0) {
      add(`- ${t.tradeoffs}: ${opt.tradeoffs.join("; ")}`);
    }
    blank();
  });

  if (toolRec.whyNotOthers.length > 0) {
    add(`**${t.whyNotOthers}**`);
    toolRec.whyNotOthers.forEach((w) => add(`- ${w.name}: ${w.reason}`));
    blank();
  }

  // DB recommendation
  add(`### ${t.dbRec}`);
  blank();
  dbRec.top3.forEach((opt, i) => {
    const pct = opt.maxScore > 0 ? Math.round((opt.score / opt.maxScore) * 100) : 100;
    add(`**${i + 1}. ${opt.name}** — ${t.score}: ${pct}%`);
    if (opt.reasons.length > 0) {
      add(`- ${t.reasons}: ${opt.reasons.join("; ")}`);
    }
    if (opt.tradeoffs.length > 0) {
      add(`- ${t.tradeoffs}: ${opt.tradeoffs.join("; ")}`);
    }
    blank();
  });

  // Deploy recommendation
  add(`### ${t.deployRec}`);
  add(`**${deployRec.platform}**`);
  deployRec.reasons.forEach((r) => add(`- ${r}`));
  blank();

  // ── Architecture Diagram ──
  add(`## 2. ${t.diagram}`);
  blank();
  add(generateMermaidArchitecture(briefing, capIds));
  blank();

  // ── Data Flow Diagram ──
  add(`## 3. ${t.dataFlowDiagram}`);
  blank();
  add(generateMermaidDataFlow(briefing, capIds));
  blank();

  // ── Data Model ──
  if (dataModel.length > 0) {
    add(`## 4. ${t.dataModel}`);
    blank();
    dataModel.forEach((table) => {
      add(`### \`${table.table}\``);
      add(`| ${options.lang === "es" ? "Campo" : "Field"} | ${options.lang === "es" ? "Tipo" : "Type"} | ${options.lang === "es" ? "Notas" : "Notes"} |`);
      add("|---|---|---|");
      table.fields.forEach((f) => {
        add(`| \`${f.name}\` | \`${f.type}\` | ${f.note || "—"} |`);
      });
      blank();
    });

    // ── DDL ──
    add(`## 5. ${t.ddl}`);
    blank();
    add(generateDdl(dataModel));
    blank();
  }

  // ── Auth Section ──
  if (capIds.includes("auth")) {
    add(`## 6. ${t.authSection}`);
    blank();
    if (options.lang === "es") {
      add("- **Método:** Email + contraseña con verificación de email");
      add("- **Sesiones:** JWT con refresh tokens (acceso: 15 min, refresh: 7 días)");
      add("- **RLS:** Row-Level Security en Supabase para aislamiento de datos");
      if (capIds.includes("roles")) {
        add("- **Roles:** admin, editor, viewer con permisos granulares");
        add("- **Políticas:** Verificación de rol en servidor y cliente");
      }
    } else {
      add("- **Method:** Email + password with email verification");
      add("- **Sessions:** JWT with refresh tokens (access: 15 min, refresh: 7 days)");
      add("- **RLS:** Row-Level Security in Supabase for data isolation");
      if (capIds.includes("roles")) {
        add("- **Roles:** admin, editor, viewer with granular permissions");
        add("- **Policies:** Server-side and client-side role checks");
      }
    }
    blank();
  }

  // ── PWA Strategy ──
  if (briefing.identity.projectType === "pwa") {
    add(`## 7. ${t.pwaSection}`);
    blank();
    if (options.lang === "es") {
      add("### Manifest");
      add("- `display: standalone`");
      add("- Iconos: 192×192 + 512×512 + maskable");
      add("- `theme_color` y `background_color` sincronizados con tokens de diseño");
      add("");
      add("### Service Worker (Workbox)");
      add("- **Precache:** Shell de la app (HTML, CSS, JS, fuentes)");
      add("- **Runtime Cache:** Stale-While-Revalidate para API, Cache-First para imágenes");
      add("- **Offline:** Cola de sincronización para mutaciones offline");
      add("- **Actualización:** Banner de 'Nueva versión disponible' con recarga");
    } else {
      add("### Manifest");
      add("- `display: standalone`");
      add("- Icons: 192×192 + 512×512 + maskable");
      add("- `theme_color` and `background_color` synced with design tokens");
      add("");
      add("### Service Worker (Workbox)");
      add("- **Precache:** App shell (HTML, CSS, JS, fonts)");
      add("- **Runtime Cache:** Stale-While-Revalidate for API, Cache-First for images");
      add("- **Offline:** Background sync queue for offline mutations");
      add("- **Update:** 'New version available' banner with reload");
    }
    blank();
  }

  // ── Performance Budgets ──
  add(`## 8. ${t.perfSection}`);
  blank();
  add("| Metric | Target |");
  add("|---|---|");
  add("| LCP (Largest Contentful Paint) | < 2.5s |");
  add("| FID (First Input Delay) | < 100ms |");
  add("| CLS (Cumulative Layout Shift) | < 0.1 |");
  add("| TTI (Time to Interactive) | < 3.5s |");
  add("| JS Bundle (main) | < 200 KB gzipped |");
  add("| Lighthouse Performance | ≥ 90 |");
  blank();

  // ── Security ──
  add(`## 9. ${t.securitySection}`);
  blank();
  if (options.lang === "es") {
    add("- Validación de entrada con Zod en cliente y servidor");
    add("- Cabeceras CSP, X-Frame-Options, X-Content-Type-Options");
    add("- Variables de entorno para secretos (nunca en el bundle)");
    add("- HTTPS obligatorio");
    if (capIds.includes("payments")) add("- Cumplimiento PCI DSS Nivel 1 vía Stripe Elements");
    if (briefing.data.entities.some(e => e.sensitivity !== "none")) {
      add("- Cifrado en reposo para datos sensibles");
      add("- Políticas de retención de datos configuradas");
    }
  } else {
    add("- Input validation with Zod on client and server");
    add("- CSP, X-Frame-Options, X-Content-Type-Options headers");
    add("- Environment variables for secrets (never in bundle)");
    add("- HTTPS required");
    if (capIds.includes("payments")) add("- PCI DSS Level 1 compliance via Stripe Elements");
    if (briefing.data.entities.some(e => e.sensitivity !== "none")) {
      add("- Encryption at rest for sensitive data");
      add("- Data retention policies configured");
    }
  }
  blank();

  // ── NFRs ──
  if (nfrs.length > 0) {
    add(`## 10. ${t.nfrSection}`);
    blank();
    nfrs.forEach((n) => add(`- ${n}`));
    blank();
  }

  // ── Traceability Matrix ──
  if (reqs.length > 0 && caps.length > 0) {
    add(`## 11. ${t.traceMatrix}`);
    blank();
    add(`| ${options.lang === "es" ? "Requisito" : "Requirement"} | ${options.lang === "es" ? "Capacidad" : "Capability"} |`);
    add("|---|---|");
    caps.forEach((cap) => {
      cap.requirements.forEach((r) => {
        const capLabel = options.lang === "es" ? cap.labelEs : cap.labelEn;
        add(`| ${r.id} | ${capLabel} |`);
      });
    });
    blank();
  }

  // ── CI/CD ──
  add(`## 12. ${t.cicdSection}`);
  blank();
  if (options.lang === "es") {
    add("- **Repositorio:** GitHub (main + feature branches)");
    add(`- **Deploy:** ${deployRec.platform} con auto-deploy desde \`main\``);
    add("- **Entornos:** Preview (por PR) → Producción (merge a main)");
    add("- **CI:** Lint + Type Check + Tests en cada PR");
  } else {
    add("- **Repository:** GitHub (main + feature branches)");
    add(`- **Deploy:** ${deployRec.platform} with auto-deploy from \`main\``);
    add("- **Environments:** Preview (per PR) → Production (merge to main)");
    add("- **CI:** Lint + Type Check + Tests on each PR");
  }
  blank();

  // ── Footer ──
  add("---");
  add(`*${t.generatedBy} · ${new Date().toISOString().split("T")[0]}*`);

  return lines.join("\n");
}
