// ─── UX Brief Builder ────────────────────────────────────────────────────────
// Generates a UX/UI Brief with screen inventories, design tokens,
// component state checklists, and copy-ready CSS/Tailwind tokens.

import type { Briefing } from "../schema";
import { getDependencyChain, getAllUxScreens, getCapabilities } from "../capabilities";

interface UxBriefOptions {
  lang: "es" | "en";
}

const l = {
  es: {
    title: "Brief de UX/UI",
    infoArch: "Arquitectura de Información",
    screenInventory: "Inventario de Pantallas",
    designTokens: "Tokens de Diseño",
    colorPalette: "Paleta de Colores",
    typography: "Tipografía",
    spacing: "Escala de Espaciado",
    radii: "Radios de Borde",
    shadows: "Sombras",
    componentStates: "Estados de Componentes",
    stateChecklist: "Lista de Verificación de Estados",
    state: "Estado",
    description: "Descripción",
    empty: "Vacío",
    loading: "Cargando",
    error: "Error",
    success: "Éxito",
    disabled: "Deshabilitado",
    a11yChecklist: "Lista de Verificación de Accesibilidad",
    cssCopy: "CSS / Tailwind — Listo para Copiar",
    generatedBy: "Generado por Vibe Coding Hub",
    density: "Densidad",
    densitySpaciousDesc: "Espacioso — mucho aire, ideal para landing pages y portfolios",
    densityBalancedDesc: "Equilibrado — para aplicaciones web generales",
    densityDenseDesc: "Denso — máxima información visible, ideal para dashboards",
  },
  en: {
    title: "UX/UI Brief",
    infoArch: "Information Architecture",
    screenInventory: "Screen Inventory",
    designTokens: "Design Tokens",
    colorPalette: "Color Palette",
    typography: "Typography",
    spacing: "Spacing Scale",
    radii: "Border Radii",
    shadows: "Shadows",
    componentStates: "Component States",
    stateChecklist: "State Checklist",
    state: "State",
    description: "Description",
    empty: "Empty",
    loading: "Loading",
    error: "Error",
    success: "Success",
    disabled: "Disabled",
    a11yChecklist: "Accessibility Checklist",
    cssCopy: "CSS / Tailwind — Ready to Copy",
    generatedBy: "Generated by Vibe Coding Hub",
    density: "Density",
    densitySpaciousDesc: "Spacious — lots of whitespace, great for landing pages and portfolios",
    densityBalancedDesc: "Balanced — for general web applications",
    densityDenseDesc: "Dense — maximum visible information, ideal for dashboards",
  },
};

function hexToOklch(hex: string): string {
  // Simplified hex → approximate OKLCH notation for the brief
  // In production you'd use a proper color library; here we provide a template
  return `oklch(0.65 0.2 ${Math.round(parseInt(hex.slice(1, 3), 16) * 1.4)})`;
}

function generatePaletteTokens(baseColor: string, density: string): string {
  const oklch = hexToOklch(baseColor);
  const spacingBase = density === "spacious" ? 6 : density === "dense" ? 3 : 4;

  return `/* ─── Design Tokens generated from base: ${baseColor} ─── */
:root {
  /* Color Palette (OKLCH) */
  --color-primary: ${oklch};
  --color-primary-soft: oklch(0.95 0.04 from var(--color-primary) h);
  --color-primary-strong: oklch(0.45 0.25 from var(--color-primary) h);
  --color-surface-1: oklch(0.99 0.002 0);
  --color-surface-2: oklch(0.96 0.004 0);
  --color-surface-3: oklch(0.93 0.006 0);
  --color-text-strong: oklch(0.15 0.01 0);
  --color-text-muted: oklch(0.45 0.02 0);
  --color-text-subtle: oklch(0.65 0.01 0);
  --color-border: oklch(0.88 0.01 0);
  --color-success: oklch(0.72 0.19 145);
  --color-warning: oklch(0.80 0.18 85);
  --color-error: oklch(0.63 0.24 25);

  /* Typography Scale (Major Third — 1.250) */
  --font-display: 'Space Grotesk Variable', system-ui, sans-serif;
  --font-body: 'Inter Variable', system-ui, sans-serif;
  --font-mono: 'JetBrains Mono Variable', monospace;
  --text-xs: 0.75rem;    /* 12px */
  --text-sm: 0.875rem;   /* 14px */
  --text-base: 1rem;     /* 16px */
  --text-lg: 1.125rem;   /* 18px */
  --text-xl: 1.25rem;    /* 20px */
  --text-2xl: 1.5rem;    /* 24px */
  --text-3xl: 1.875rem;  /* 30px */
  --text-4xl: 2.25rem;   /* 36px */
  --text-5xl: 3rem;      /* 48px */

  /* Spacing Scale (base: ${spacingBase}px) */
  --space-1: ${spacingBase * 1}px;
  --space-2: ${spacingBase * 2}px;
  --space-3: ${spacingBase * 3}px;
  --space-4: ${spacingBase * 4}px;
  --space-5: ${spacingBase * 5}px;
  --space-6: ${spacingBase * 6}px;
  --space-8: ${spacingBase * 8}px;
  --space-10: ${spacingBase * 10}px;
  --space-12: ${spacingBase * 12}px;
  --space-16: ${spacingBase * 16}px;

  /* Border Radii */
  --radius-sm: 6px;
  --radius-md: 10px;
  --radius-lg: 16px;
  --radius-xl: 24px;
  --radius-full: 9999px;

  /* Shadows */
  --shadow-xs: 0 1px 2px oklch(0 0 0 / 0.05);
  --shadow-sm: 0 2px 4px oklch(0 0 0 / 0.06);
  --shadow-md: 0 4px 12px oklch(0 0 0 / 0.08);
  --shadow-lg: 0 8px 24px oklch(0 0 0 / 0.1);
}

/* Dark Mode Override */
.dark {
  --color-surface-1: oklch(0.16 0.01 0);
  --color-surface-2: oklch(0.20 0.012 0);
  --color-surface-3: oklch(0.24 0.014 0);
  --color-text-strong: oklch(0.96 0.005 0);
  --color-text-muted: oklch(0.70 0.02 0);
  --color-text-subtle: oklch(0.50 0.01 0);
  --color-border: oklch(0.30 0.01 0);
}`;
}

export function buildUxBrief(briefing: Briefing, options: UxBriefOptions): string {
  const t = l[options.lang];
  const capIds = getDependencyChain(briefing.capabilities.selected);
  const screens = getAllUxScreens(capIds);
  const caps = getCapabilities(capIds);
  const isEs = options.lang === "es";

  const lines: string[] = [];
  const add = (s: string) => lines.push(s);
  const blank = () => lines.push("");

  add(`# ${t.title}`);
  add(`**${briefing.identity.name || "—"}**`);
  blank();

  // ── Information Architecture ──
  add(`## 1. ${t.infoArch}`);
  blank();
  if (isEs) {
    add("### Navegación Principal");
    add("- Inicio / Landing");
  } else {
    add("### Main Navigation");
    add("- Home / Landing");
  }
  if (capIds.includes("auth")) add(isEs ? "- Registro / Inicio de sesión" : "- Sign Up / Login");
  add(isEs ? "- Dashboard / Panel principal" : "- Dashboard / Main Panel");
  caps.forEach((cap) => {
    const capScreens = cap.uxScreens;
    if (capScreens.length > 0) {
      add(`- ${isEs ? cap.labelEs : cap.labelEn}`);
    }
  });
  if (capIds.includes("admin")) add(isEs ? "- Panel de Administración" : "- Admin Panel");
  blank();

  // ── Screen Inventory ──
  add(`## 2. ${t.screenInventory}`);
  blank();
  add(`| ${isEs ? "Pantalla" : "Screen"} | ${isEs ? "Capacidad" : "Capability"} | ${isEs ? "Prioridad" : "Priority"} |`);
  add("|---|---|---|");
  add(`| \`home\` | — | ${isEs ? "Obligatorio" : "Required"} |`);
  if (capIds.includes("auth")) {
    add(`| \`login\` | Auth | ${isEs ? "Obligatorio" : "Required"} |`);
    add(`| \`register\` | Auth | ${isEs ? "Obligatorio" : "Required"} |`);
  }
  caps.forEach((cap) => {
    cap.uxScreens.forEach((screen) => {
      const capLabel = isEs ? cap.labelEs : cap.labelEn;
      const priority = cap.requirements.some(r => r.priority === "must") ?
        (isEs ? "Obligatorio" : "Required") : (isEs ? "Recomendado" : "Recommended");
      add(`| \`${screen}\` | ${capLabel} | ${priority} |`);
    });
  });
  blank();

  // ── Design Tokens ──
  add(`## 3. ${t.designTokens}`);
  blank();

  // Tone
  if (briefing.branding.toneAdjectives.length > 0) {
    add(`### ${isEs ? "Tono Visual" : "Visual Tone"}`);
    add(briefing.branding.toneAdjectives.map(a => `**${a}**`).join(" · "));
    blank();
  }

  // Density
  add(`### ${t.density}`);
  const densityDesc = briefing.branding.density === "spacious" ? t.densitySpaciousDesc
    : briefing.branding.density === "dense" ? t.densityDenseDesc
    : t.densityBalancedDesc;
  add(`**${briefing.branding.density}** — ${densityDesc}`);
  blank();

  // CSS tokens
  add(`### ${t.cssCopy}`);
  blank();
  add("```css");
  add(generatePaletteTokens(briefing.branding.baseColor, briefing.branding.density));
  add("```");
  blank();

  // ── Component States ──
  add(`## 4. ${t.componentStates}`);
  blank();
  if (isEs) {
    add("Cada componente interactivo **debe** implementar estos 5 estados:");
  } else {
    add("Every interactive component **must** implement these 5 states:");
  }
  blank();
  add(`| ${t.state} | ${t.description} |`);
  add("|---|---|");
  add(`| ${t.empty} | ${isEs ? "Sin datos — muestra ilustración y CTA para empezar" : "No data — show illustration and CTA to get started"} |`);
  add(`| ${t.loading} | ${isEs ? "Skeleton loader animado (no spinner)" : "Animated skeleton loader (not spinner)"} |`);
  add(`| ${t.error} | ${isEs ? "Mensaje claro + botón de reintentar" : "Clear message + retry button"} |`);
  add(`| ${t.success} | ${isEs ? "Confirmación visual (toast o inline)" : "Visual confirmation (toast or inline)"} |`);
  add(`| ${t.disabled} | ${isEs ? "Reducir opacidad + cursor not-allowed + tooltip explicando por qué" : "Reduce opacity + cursor not-allowed + tooltip explaining why"} |`);
  blank();

  // ── Accessibility Checklist ──
  add(`## 5. ${t.a11yChecklist}`);
  blank();
  if (isEs) {
    add("- [ ] Contraste de color ≥ 4.5:1 para texto (WCAG AA)");
    add("- [ ] Todos los elementos interactivos tienen foco visible");
    add("- [ ] Navegación completa con teclado (Tab, Enter, Escape)");
    add("- [ ] Todas las imágenes tienen `alt` descriptivo");
    add("- [ ] Formularios con `<label>` asociado y anuncio de errores");
    add("- [ ] `prefers-reduced-motion` respetado en animaciones");
    add("- [ ] `prefers-color-scheme` respetado para modo oscuro automático");
    add("- [ ] Semántica HTML correcta (`<nav>`, `<main>`, `<aside>`, `<header>`, `<footer>`)");
    add("- [ ] `aria-live` para actualizaciones dinámicas");
    add("- [ ] Touch targets ≥ 44×44px en móvil");
  } else {
    add("- [ ] Color contrast ≥ 4.5:1 for text (WCAG AA)");
    add("- [ ] All interactive elements have visible focus");
    add("- [ ] Full keyboard navigation (Tab, Enter, Escape)");
    add("- [ ] All images have descriptive `alt` text");
    add("- [ ] Forms with associated `<label>` and error announcements");
    add("- [ ] `prefers-reduced-motion` respected in animations");
    add("- [ ] `prefers-color-scheme` respected for automatic dark mode");
    add("- [ ] Correct HTML semantics (`<nav>`, `<main>`, `<aside>`, `<header>`, `<footer>`)");
    add("- [ ] `aria-live` for dynamic updates");
    add("- [ ] Touch targets ≥ 44×44px on mobile");
  }
  blank();

  add("---");
  add(`*${t.generatedBy} · ${new Date().toISOString().split("T")[0]}*`);

  return lines.join("\n");
}
